--- 
jobs: 
  build: 
    docker: 
      - 
        image: "circleci/android:api-25-alpha"
    environment: 
      JVM_OPTS: "-Xmx3200m"
    steps: 
      - checkout
      - 
        restore_cache: 
          key: "jars-{{ checksum \"build.gradle\" }}-{{ checksum \"app/build.gradle\" }}"
      - 
        run: 
          command: "./gradlew androidDependencies"
          name: "Download Dependencies"
      - 
        save_cache: 
          key: "jars-{{ checksum \"build.gradle\" }}-{{ checksum \"app/build.gradle\" }}"
          paths: 
            - ~/.gradle
      - 
        run: 
          command: "gradle runDebugBuildOnBrowserstack"
          name: "Run Tests"
      - 
        store_artifacts: 
          destination: reports
          path: app/build/reports
      - 
        store_test_results: 
          path: app/build/test-results
    working_directory: ~/browserstack-espresso-gradleplugin    
version: 2
